
-- Get Top 10 movies by avergaerating in comedy and romance genre(includes both). From the year 2011 and 2015 with minimum votes of 50000 and print the lead actor names

set pagesize 100
set linesize 300
column GENRES format a30
column PRIMARYTITLE format a30
column STARTYEAR format a30
column PRIMARYNAME format a30 
set echo on
SPOOL IMDB.txt
 SELECT Distinct PRIMARYTITLE, AVERAGERATING,GENRES,PRIMARYNAME FROM sharmac.TITLE_RATINGS R, sharmac.TITLE_BASICS B, sharmac.NAME_BASICS N, sharmac.TITLE_PRINCIPALS P
 WHERE R.TCONST = B.TCONST AND B.TCONST = P.TCONST AND P.NCONST = N.NCONST AND GENRES LIKE '%Comedy%Romance%' AND STARTYEAR BETWEEN '2011' AND '2015' AND TITLETYPE = 'movie'
 AND NUMVOTES >=50000 AND P.ORDERING = '1'
 ORDER BY  AVERAGERATING DESC
 FETCH FIRST 10 ROWS ONLY ;
 SPOOL OFF



 Explain plan for SELECT Distinct PRIMARYTITLE, AVERAGERATING,GENRES,PRIMARYNAME FROM sharmac.TITLE_RATINGS R, sharmac.TITLE_BASICS B, sharmac.NAME_BASICS N, sharmac.TITLE_PRINCIPALS P
 WHERE R.TCONST = B.TCONST AND B.TCONST = P.TCONST AND P.NCONST = N.NCONST AND GENRES LIKE '%Comedy%Romance%' AND STARTYEAR BETWEEN '2011' AND '2015' AND TITLETYPE = 'movie'
 AND NUMVOTES >=50000 AND P.ORDERING = '1'
 ORDER BY  AVERAGERATING DESC
 FETCH FIRST 10 ROWS ONLY ;
 

 SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
